2020-04-25 14:24:23,940 ERROR: Exception on /followed_posts/dongjohn [GET] [in /Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andrew.xia/Documents/Github/flasky/app/routes.py", line 38, in followed_posts
    return render_template('user.html', user=user, posts=posts)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/user.html", line 27, in block "content"
    {% include '_post.html' %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2020-04-25 14:25:18,180 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:25:20,261 ERROR: Exception on /followed_posts/dongjohn [GET] [in /Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andrew.xia/Documents/Github/flasky/app/routes.py", line 38, in followed_posts
    return render_template('user.html', user=user, posts=posts)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/user.html", line 27, in block "content"
    {% include '_post.html' %}
  File "/Users/andrew.xia/Documents/Github/flasky/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2020-04-25 14:25:53,289 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:39:05,056 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:42:13,600 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:45:35,559 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:47:55,849 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:45]
2020-04-25 14:57:41,373 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:48]
2020-04-25 16:40:37,915 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:48]
2020-04-25 16:40:54,127 ERROR: Exception on /reset_password_request [POST] [in /Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrew.xia/Documents/Github/flasky/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andrew.xia/Documents/Github/flasky/app/routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "/Users/andrew.xia/Documents/Github/flasky/app/email.py", line 11, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/andrew.xia/Documents/Github/flasky/app/models.py", line 61, in get_reset_password_token
    return jwt.encode(
NameError: name 'jwt' is not defined
2020-04-25 16:42:06,727 INFO: Microblog startup [in /Users/andrew.xia/Documents/Github/flasky/app/__init__.py:48]
